{
 "title": "Dispute Monitor",
 "description": "Display metrics from op-dispute-mon",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(op_dispute_mon_up,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(op_dispute_mon_up{cluster=\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Monitored Games",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(op_dispute_mon_games_agreement{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(op_dispute_mon_games_agreement{cluster=${cluster:doublequote},namespace=${namespace:doublequote}, completion=\"in_progress\"})",
     "legendFormat": "In Progress"
    },
    {
     "expr": "sum(op_dispute_mon_ignored_games{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "Ignored"
    }
   ]
  },
  {
   "title": "Incorrect Forecast",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(op_dispute_mon_games_agreement{cluster=${cluster:doublequote},namespace=${namespace:doublequote}, result_correctness=\"incorrect\", completion=\"in_progress\"})",
     "legendFormat": "Forecast"
    }
   ]
  },
  {
   "title": "Last Output Root Fetch Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(time() - op_dispute_mon_last_output_fetch{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Invalid Proposal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(time() - op_dispute_mon_latest_proposal{root_agreement=\"disagree\", cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "op_dispute_mon_info{cluster=${cluster:doublequote},namespace=${namespace:doublequote}}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  { "title": "Dispute Mon Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 4, "x": 20, "y": 3 } },
  {
   "title": "Incorrect Result",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(op_dispute_mon_games_agreement{cluster=${cluster:doublequote},namespace=${namespace:doublequote}, result_correctness=\"incorrect\", completion=\"complete\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "min(op_dispute_mon_up{namespace=\"op-dispute-mon\"}) > 0",
     "legendFormat": "1 if dispute mon is up"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Credits Exceeding Expectation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(op_dispute_mon_credits{cluster=${cluster:doublequote},namespace=${namespace:doublequote}, credit=\"above\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Insufficient Credits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(op_dispute_mon_credits{cluster=${cluster:doublequote},namespace=${namespace:doublequote}, credit=\"below\", withdrawable=\"non_withdrawable\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Underfunded WETH Contract Addrs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (delayedWETH) (op_dispute_mon_bond_collateral_available{cluster=${cluster:doublequote},namespace=${namespace:doublequote}, balance=\"insufficient\"}) > 0",
     "legendFormat": "{{delayedWETH}}"
    }
   ]
  },
  {
   "title": "Early Claim Resolution",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(op_dispute_mon_claims{cluster=${cluster:doublequote},namespace=${namespace:doublequote}, resolved=\"resolved\", game_time_period=\"first_half\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wrong Leader",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(op_dispute_mon_games_agreement{cluster=${cluster:doublequote},namespace=${namespace:doublequote}, result_correctness=\"incorrect\", completion=\"in_progress\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Divergent Credits",
   "type": "stat",
   "description": "Number of withdrawal requests that diverge from the credits mapping.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(op_dispute_mon_withdrawal_requests{cluster=${cluster:doublequote},namespace=${namespace:doublequote}, credits=\"divergent\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lost Bonds",
   "type": "stat",
   "description": "Number of bonds lost by an honest actor.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(op_dispute_mon_honest_actor_bonds{cluster=${cluster:doublequote},namespace=${namespace:doublequote}, state=\"lost\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Honest Actor Errors",
   "type": "stat",
   "description": "Count of invalid claims made by honest actors.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(op_dispute_mon_honest_actor_claims{cluster=${cluster:doublequote},namespace=${namespace:doublequote},state=\"invalid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resolvable Claims",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(op_dispute_mon_claims{cluster=${cluster:doublequote},namespace=${namespace:doublequote}, resolved=\"unresolved\", resolvable=\"resolvable\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid L2 Block Challenge",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, job) (op_dispute_mon_l2_block_challenges{cluster=${cluster:doublequote},namespace=${namespace:doublequote}, root_agreement=\"agree\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Game Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Games",
   "type": "timeseries",
   "description": "Tracked games broken down by actual status",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace) (op_dispute_mon_games_agreement{cluster=${cluster:doublequote},namespace=${namespace:doublequote}, completion=\"in_progress\"})",
     "legendFormat": "In Progress"
    },
    {
     "expr": "sum by (cluster, namespace) (op_dispute_mon_games_agreement{cluster=${cluster:doublequote},namespace=${namespace:doublequote}, completion=\"complete\", status=~\".*challenger_wins\"})",
     "legendFormat": "Challenger Wins"
    },
    {
     "expr": "sum by (cluster, namespace) (op_dispute_mon_games_agreement{cluster=${cluster:doublequote},namespace=${namespace:doublequote}, completion=\"complete\", status=~\".*defender_wins\"})",
     "legendFormat": "Defender Wins"
    },
    {
     "expr": "sum by (cluster, namespace) (op_dispute_mon_ignored_games{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "Ignored"
    }
   ]
  },
  {
   "title": "Current Status Agreement",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (status) (op_dispute_mon_games_agreement{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Game Agreement",
   "type": "timeseries",
   "description": "Tracked games broken down by actual status",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (status, cluster, namespace, job) (op_dispute_mon_games_agreement{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Forecast Expected Result",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (result_correctness) (op_dispute_mon_games_agreement{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Honest Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Honest Claims",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (cluster, namespace, job, honest_actor_address, state) (op_dispute_mon_honest_actor_claims{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "{{honest_actor_address}} {{state}}"
    }
   ]
  },
  {
   "title": "Honest Bonds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "expr": "max by (cluster, namespace, job, honest_actor_address, state) (op_dispute_mon_honest_actor_bonds{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "{{honest_actor_address}} {{state}}"
    }
   ]
  },
  { "title": "Bonds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Bond Collateral",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, job, delayedWETH) (op_dispute_mon_bond_collateral_required{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "Required {{delayedWETH}}"
    },
    {
     "expr": "sum by (cluster, namespace, job, delayedWETH) (op_dispute_mon_bond_collateral_available{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "Available  {{delayedWETH}}"
    }
   ]
  },
  {
   "title": "Bond Collateralisation",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (balance) (op_dispute_mon_bond_collateral_required{cluster=${cluster:doublequote},namespace=${namespace:doublequote}})",
     "legendFormat": "{{balance}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Log Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "count_over_time ({cluster=\"$cluster\", app=\"op-dispute-mon\"} | logfmt lvl | label_format level=lvl | level != \"\" | drop node_name, pod [5m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", namespace=\"$namespace\"} |= `` | logfmt | lvl =~ `err?or` | label_format level=lvl"
    }
   ]
  },
  {
   "title": "Warn Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", namespace=\"$namespace\"} |= `` | logfmt | lvl = `warn` | label_format level=lvl"
    }
   ]
  },
  {
   "title": "Full Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", namespace=\"$namespace\"} |= `` | logfmt | label_format level=lvl"
    }
   ]
  }
 ]
}